### ISSUE TITLE
Team affective task discussion period

### ISSUE THREAD

**Issue by eduongAZ** [ml4ai/tomcat-baseline-tasks#26]
After showing the image for some time, include the word "discuss" underneath the image and keep it there for some time until the rating period.

The team affective task should have this sequence:
1. Show picture to each participant for some period of time.
2. Then keep showing that same picture, but include the word "discuss" underneath the picture for some period of time.
3. Then show rating screen, but only one participant can select the rating.

**Comment by CalebUAz** [comment]
1. If the timer is set to 20 seconds, then they have 10 seconds to analyze, and then for the next 10 seconds a text appears "Discuss with the other members!". 
2.  Same as before. 
3. Didn't implement that yet
