### ISSUE TITLE
Affective task: server timestamp events

### ISSUE THREAD

**Issue by eduongAZ** [ml4ai/tomcat-baseline-tasks#40]
This includes when the participants see a picture, when they see the rating, when they click on any of the rating box, and when they hit submit

**Comment by adarshp** [comment]
Related issue: https://github.com/ml4ai/tomcat-baseline-tasks/issues/44

**Comment by adarshp** [comment]
Another related issue: https://github.com/ml4ai/tomcat-baseline-tasks/issues/45

**Comment by eduongAZ** [comment]
Duplicate of https://github.com/ml4ai/tomcat-baseline-tasks/issues/45

**Comment by eduongAZ** [comment]
https://github.com/ml4ai/tomcat-baseline-tasks/issues/45
