### ISSUE TITLE
Baseline task data collection running on ToM, storing data on CAT

### ISSUE THREAD

**Issue by eduongAZ** [ml4ai/tomcat-baseline-tasks#44]
@adarshp suggested using ELK to store baseline task data on CAT while running the server on ToM.

**Comment by adarshp** [comment]
There are three components that can live on separate machines or the same machine: 

- ELK stack (3 containers)
- MQTT container
- Minecraft container

Messages from the Minecraft container travel to the MQTT container, which then pushes them to the ELK stack. Depending on the desired latency and timestamp generation machine, we can put these three components on one machine (like we currently have with TOM), or split them among TOM and CAT.

**Comment by eduongAZ** [comment]
After discussing with Chinmai and Kobus, it seems that the if the time differences between ToM and CAT are less than a millisecond, then there is no need to have CAT receiving the data, putting the timestamp, and storing locally on CAT. 

We will run the baseline task server on ToM and writing to CAT NFS folder using ToM timestamp.
