### ISSUE TITLE
Implement recording all actions participants do in the affective task.

### ISSUE THREAD

**Issue by eduongAZ** [ml4ai/tomcat-baseline-tasks#45]

**Comment by adarshp** [comment]
Right now, the affective task only records whenever participant submits scoring (valence, arousal). @val-pf suggested recording all actions taken by participants to correlate with brain scanning signals.

**Comment by adarshp** [comment]
@adarshp suggestion: Just publish the action messages to the message bus - if the ELK stack and MQTT message bus are running (i.e., the testbed), all the messages will automatically be ingested into the Elasticsearch database. Use the [`paho-mqtt`](https://pypi.org/project/paho-mqtt/) to interface with the message bus.

**Comment by adarshp** [comment]
To verify that things work, go to the Kibana interface. If you are accessing it through a browser on the iMac, ensure that port 5601 is forwarded from that iMac to the computer that the ELK stack is running on. If you are running everything locally on your laptop, no port forwarding is necessary.

**Comment by adarshp** [comment]
If you don't like GUIs, there are libraries out there that can query Elasticsearch databases. In that case, you will need to ensure that the computer where you are running your query program has port 9200 forwarded to the computer where the ELK stack is running (if they are different computers).

**Comment by adarshp** [comment]
This issue is dependent on #44
