### ISSUE TITLE
Validate baseline tasks data

### ISSUE THREAD

**Issue by eduongAZ** [ml4ai/tomcat-baseline-tasks#46]

**Comment by CalebUAz** [comment]
So I did a dry run today and had a look at the baseline tasks data. It appears fine to me. 

1. rest state: [1657821355.csv](https://github.com/ml4ai/tomcat-baseline-tasks/files/9114757/1657821355.csv)
2. Affective task individual: [individual_caleb_1657821447.csv](https://github.com/ml4ai/tomcat-baseline-tasks/files/9114752/individual_caleb_1657821447.csv)
3. Affective task team: [team_1657821974.csv](https://github.com/ml4ai/tomcat-baseline-tasks/files/9114755/team_1657821974.csv)
4.  Finger tapping: [1657821416.csv](https://github.com/ml4ai/tomcat-baseline-tasks/files/9114762/1657821416.csv)
5. Ping pong competitive: [competitive_0_1657822519.csv](https://github.com/ml4ai/tomcat-baseline-tasks/files/9114771/competitive_0_1657822519.csv)
6. Ping pong cooperative: [cooperative_0_1657822684.csv](https://github.com/ml4ai/tomcat-baseline-tasks/files/9114778/cooperative_0_1657822684.csv)

@eduongAZ you can close the issue if you feel it looks good to you!

**Comment by eduongAZ** [comment]
The validation needs to be automated. We need a script that will run after every experiment to check the validity of the generated data, since we will be publishing such data, we need know which data is corrupted.

**Comment by CalebUAz** [comment]
@eduongAZ Well we can add a script to baseline task itself that checks the data before moving on with the next task, in case the data is corrupted we can repeat the baseline task. 

For data validation what do you have in mind?

**Comment by CalebUAz** [comment]
### **Baseline task data validation:**

![Image](https://user-images.githubusercontent.com/90938130/182488112-7af9b943-9854-4b92-8063-98bdd23eb53e.png)

**To execute:** `python3 baseline-tasks-data-validation.py --p \path_to_baseline_task_data --s subjectID1 --s subjectID2 --s  subjectID3` 

[Baselinetask data validation](https://github.com/ml4ai/tomcat/blob/human_experiments_updates/human_experiments/lab_software/tomcat-baseline-tasks/baseline-tasks-data-validation.py) does the following:

1. Check if folders **['finger_tapping', 'rest_state', 'affective', 'ping_pong']** exist or not.
2. Counts number of csv files under each of folders. 
3. Checks if the CSV files are empty or not. 
4. Displays start- and stop- time of the particular task. 
5. Calculates how long a task took to complete and checks if its within the range mentioned in task config file. 
6. Reads Subject ID from the CSV file and compares it to subject ID passed as argument. 

If it doesn't fulfill the above condition then at that step it will show the error in red with a cross mark at the end like:

![Image](https://user-images.githubusercontent.com/90938130/182491377-a9da704c-3015-43a6-9e70-2cf50bd8f920.png)
